version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle update --bundler 
      - run:
          command: bundle exec rspec
workflows:
  version: 2
  build_and_test:
    jobs:
      - test